server:
  port: 8080
spring:
  application:
    name: service-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://120.78.88.169:8763/eureka/,http://120.78.88.169:8761/eureka/,http://120.78.88.169:8762/eureka/
feign:
  hystrix:
    enabled: true
