server:
  port: 8081
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhsot:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
feign:
  hystrix:
    enabled: true
